"""MolmoWeb-vocabulary environment feedback for coordinate-clicking students.

Why this exists
---------------
The MolmoWeb SFT corpora were generated in MolmoWeb's own environment, whose
per-step feedback strings differ from this repo's:

    this harness : Succeed: `click` on <li> "Firehose..." at (492, 217) executed.
                   Note: no visible navigation or new tab detected.
    MolmoWeb     : Succeed: left click on textbox with value 'Search the site'
                   (element is clickable)

A student trained on the latter reads the former on every step and cannot tell
whether its action worked, which shows up as degenerate single-action loops
(click x29 at one pixel, wait x29) that never call done(). The baseline
OpenWebRL corpus does not have this problem: it was generated by this harness,
so its strings match character for character.

This module re-renders the feedback in MolmoWeb's vocabulary. It is opt-in
(SLIME_BROWSER_MOLMOWEB_FEEDBACK=1) and scoped to those checkpoints -- every
other model must keep the harness's native strings, which is what it trained on.

Resolving a coordinate back to an element
-----------------------------------------
MolmoWeb addressed elements by bid (`click(bid='158')`) and described the node
it addressed. The training coordinates are that node's bbox centre -- see
_bbox_center in sft/conversion/convert_molmoweb_to_openai_messages.py. So the
question a description must answer is "which element's box is this the centre
of", NOT "what is painted on top of this pixel".

That distinction is the whole ballgame. document.elementFromPoint answers the
second question and scores 74% exact on well-aimed clicks, because overlays and
sticky headers intercept the hit test -- occlusion MolmoWeb never saw, since
addressing by bid bypasses hit-testing. Matching against element bounding boxes
answers the first and scores 99% (measured, 163 well-aimed points across 8
sites). Hence bbox matching below.

Ported from MolmoWeb's utils/axtree/axtree.py, which is sync Playwright; this
harness is async, so the CDP/evaluate calls are awaited here. Extraction logic
and the CDP payloads are otherwise unchanged.
"""

from __future__ import annotations

import os
import re
from typing import Any

from loguru import logger

_MOLMOWEB_ROOT = os.environ.get("SLIME_BROWSER_MOLMOWEB_ROOT", "/mmfs1/home/dan29/molmoweb")
_JS_DIR = os.path.join(_MOLMOWEB_ROOT, "utils", "axtree", "javascript")

BID_ATTR = "bid"
VIS_ATTR = "molmoweb_visibility_ratio"
SOM_ATTR = "molmoweb_set_of_marks"

_BID_REGEX = re.compile(r"^molmoweb_id_([a-zA-Z0-9]+)\s?(.*)")

_SKIP_URL_PREFIXES = (
    "chrome-error://", "chrome://", "chrome-extension://", "devtools://",
    "edge://", "data:", "blob:", "file://",
)
_AD_MARKERS = (
    "ads.", "ad.", "advertising.", "adserver.", "analytics.", "tracking.", "track.",
    "pixel.", "beacon.", "doubleclick", "googlesyndication", "amazon-adsystem",
    "pubmatic", "rubicon", "criteo", "adsystem",
)

# Roles the MolmoWeb corpus actually contains. Anything outside this set was
# never a click target for the teacher, so naming it would be out-of-vocabulary;
# such clicks fall back to the corpus's own bid template instead.
MOLMOWEB_ROLES = frozenset({
    "link", "button", "textbox", "combobox", "searchbox", "option",
    "tab", "navigation", "heading", "image", "radio", "group",
})


def enabled() -> bool:
    return os.environ.get("SLIME_BROWSER_MOLMOWEB_FEEDBACK", "").strip() == "1"


def _is_skip_frame(url: str) -> bool:
    if not url or url in ("about:blank", "about:srcdoc"):
        return True
    low = url.lower()
    if low.startswith(_SKIP_URL_PREFIXES) or "chromewebdata" in low:
        return True
    if "captcha" in low or "recaptcha" in low:
        return True
    return any(m in low for m in _AD_MARKERS)


def _load_js(name: str) -> str:
    with open(os.path.join(_JS_DIR, name)) as f:
        return f.read()


def _extract_bid_from_aria(s: str) -> tuple[list, str]:
    m = _BID_REGEX.fullmatch(s)
    if not m:
        return [], s
    return list(m.groups()[:-1]), m.groups()[-1]


async def _mark_elements(page, tags_to_mark: str = "standard_html") -> None:
    js = _load_js("frame_mark_elements.js")

    async def _recurse(frame, frame_bid: str):
        if _is_skip_frame(frame.url):
            return
        await frame.evaluate(js, [frame_bid, BID_ATTR, tags_to_mark])
        for child in frame.child_frames:
            if child.is_detached():
                continue
            elem = await child.frame_element()
            if await elem.content_frame() != child:
                continue
            sandbox = await elem.get_attribute("sandbox")
            if sandbox is not None and "allow-scripts" not in sandbox.split():
                continue
            child_bid = await elem.get_attribute(BID_ATTR)
            if child_bid is None:
                continue  # lenient: skip unmarkable frames rather than raising
            await _recurse(child, child_bid)

    await _recurse(page.main_frame, "")


async def _unmark_elements(page) -> None:
    js = _load_js("frame_unmark_elements.js")
    for frame in page.frames:
        if _is_skip_frame(frame.url):
            continue
        try:
            if frame != page.main_frame:
                elem = await frame.frame_element()
                if await elem.content_frame() != frame:
                    continue
                sandbox = await elem.get_attribute("sandbox")
                if sandbox is not None and "allow-scripts" not in sandbox.split():
                    continue
                if await elem.get_attribute(BID_ATTR) is None:
                    continue
            await frame.evaluate(js)
        except Exception as exc:
            if "detached" not in str(exc).lower():
                raise


async def _extract_dom_snapshot(page) -> dict:
    cdp = await page.context.new_cdp_session(page)
    try:
        snap = await cdp.send("DOMSnapshot.captureSnapshot", {
            "computedStyles": [], "includeDOMRects": True, "includePaintOrder": True,
        })
    finally:
        await cdp.detach()

    for attr_name in ("aria-roledescription", "aria-description"):
        try:
            attr_id = snap["strings"].index(attr_name)
        except ValueError:
            continue
        seen = set()
        for doc in snap["documents"]:
            for node_attrs in doc["nodes"]["attributes"]:
                for i in range(0, len(node_attrs), 2):
                    if node_attrs[i] == attr_id:
                        vid = node_attrs[i + 1]
                        if vid not in seen:
                            _, cleaned = _extract_bid_from_aria(snap["strings"][vid])
                            snap["strings"][vid] = cleaned
                            seen.add(vid)
                        if snap["strings"][vid] == "":
                            del node_attrs[i:i + 2]
                        break
    return snap


async def _extract_merged_axtree(page) -> dict:
    cdp = await page.context.new_cdp_session(page)
    try:
        tree = await cdp.send("Page.getFrameTree")
        frame_ids, queue = [], [tree["frameTree"]]
        while queue:
            f = queue.pop()
            queue.extend(f.get("childFrames", []))
            frame_ids.append(f["frame"]["id"])

        frame_trees = {}
        for fid in frame_ids:
            try:
                frame_trees[fid] = await cdp.send("Accessibility.getFullAXTree", {"frameId": fid})
            except Exception as exc:
                # Frames can vanish between getFrameTree and the AX query.
                logger.debug(f"AXTree: frame {fid} unavailable: {type(exc).__name__}")

        for ax in frame_trees.values():
            for node in ax["nodes"]:
                items = []
                if "properties" in node:
                    for i, p in enumerate(node["properties"]):
                        if p["name"] == "roledescription":
                            items, new = _extract_bid_from_aria(p["value"]["value"])
                            p["value"]["value"] = new
                            if not new:
                                del node["properties"][i]
                            break
                if "description" in node:
                    items2, new = _extract_bid_from_aria(node["description"]["value"])
                    node["description"]["value"] = new
                    if not new:
                        del node["description"]
                    if not items:
                        items = items2
                if items:
                    node["molmoweb_id"] = items[0]

        merged: dict[str, list] = {"nodes": []}
        for ax in frame_trees.values():
            merged["nodes"].extend(ax["nodes"])
        return merged
    finally:
        await cdp.detach()


def _extract_extra_properties(dom_snapshot: dict) -> dict:
    """Unchanged from MolmoWeb: pure post-processing of the DOM snapshot."""
    strings = dom_snapshot["strings"]

    def _str(idx):
        return strings[idx] if idx != -1 else None

    def _find_str_id(s):
        try:
            return strings.index(s)
        except ValueError:
            return -1

    bid_id, vis_id, som_id = _find_str_id(BID_ATTR), _find_str_id(VIS_ATTR), _find_str_id(SOM_ATTR)

    doc_meta: dict[int, dict[str, Any]] = {0: {"parent": None}}
    to_process = [0]
    while to_process:
        doc_idx = to_process.pop()
        doc = dom_snapshot["documents"][doc_idx]
        children = doc["nodes"]["contentDocumentIndex"]
        for node_idx, child_doc in zip(children["index"], children["value"]):
            doc_meta[child_doc] = {"parent": {"doc": doc_idx, "node": node_idx}}
            to_process.append(child_doc)

        parent = doc_meta[doc_idx]["parent"]
        abs_x = abs_y = 0.0
        if parent:
            pdoc, pnode = parent["doc"], parent["node"]
            try:
                li = dom_snapshot["documents"][pdoc]["layout"]["nodeIndex"].index(pnode)
                bounds = dom_snapshot["documents"][pdoc]["layout"]["bounds"][li]
                abs_x = doc_meta[pdoc]["abs_x"] + bounds[0]
                abs_y = doc_meta[pdoc]["abs_y"] + bounds[1]
            except ValueError:
                pass

        doc_meta[doc_idx]["abs_x"] = abs_x - doc["scrollOffsetX"]
        doc_meta[doc_idx]["abs_y"] = abs_y - doc["scrollOffsetY"]

        n_nodes = len(doc["nodes"]["parentIndex"])
        nodes = [{"bid": None, "vis": None, "bbox": None, "click": False, "som": None}
                 for _ in range(n_nodes)]

        for ni in doc["nodes"]["isClickable"]["index"]:
            nodes[ni]["click"] = True

        for ni, attrs in enumerate(doc["nodes"]["attributes"]):
            for i in range(0, len(attrs), 2):
                nid, vid = attrs[i], attrs[i + 1]
                if nid == bid_id:
                    nodes[ni]["bid"] = _str(vid)
                elif nid == vis_id:
                    nodes[ni]["vis"] = float(_str(vid))
                elif nid == som_id:
                    nodes[ni]["som"] = _str(vid) == "1"

        for ni, bounds, cr in zip(
            doc["layout"]["nodeIndex"], doc["layout"]["bounds"], doc["layout"]["clientRects"],
        ):
            if cr:
                b = list(bounds)
                b[0] += doc_meta[doc_idx]["abs_x"]
                b[1] += doc_meta[doc_idx]["abs_y"]
                nodes[ni]["bbox"] = b

        doc_meta[doc_idx]["nodes"] = nodes

    result = {}
    for dm in doc_meta.values():
        for n in dm.get("nodes", []):
            if n["bid"]:
                result[n["bid"]] = {
                    "visibility": n["vis"],
                    "bbox": n["bbox"],
                    "clickable": n["click"],
                    "set_of_marks": n["som"],
                }
    return result


async def extract_axtree(page) -> tuple[dict, dict]:
    """Async port of MolmoWeb's extract_axtree: (merged axtree, extra properties)."""
    await _mark_elements(page)
    try:
        dom = await _extract_dom_snapshot(page)
        axtree = await _extract_merged_axtree(page)
        extra = _extract_extra_properties(dom)
    finally:
        await _unmark_elements(page)
    return axtree, extra


# ---------------------------------------------------------------------------
# Coordinate -> element -> MolmoWeb description
# ---------------------------------------------------------------------------

def _ax_index(axtree: dict) -> dict:
    return {n["molmoweb_id"]: n for n in axtree.get("nodes", [])
            if n.get("molmoweb_id") is not None}


def _role_name(node) -> tuple[str | None, str]:
    if not node:
        return None, ""
    return node.get("role", {}).get("value"), node.get("name", {}).get("value", "")


def resolve_click_target(axtree: dict, extra: dict, x: float, y: float):
    """Smallest visible bbox containing (x, y) whose AX role is in MolmoWeb's
    vocabulary; ties broken by distance from the bbox centre to the click.

    Inverse of the corpus's bid -> bbox-centre mapping, so a click at an
    element's centre resolves back to that element. Deliberately ignores paint
    order: the corpus described the addressed element regardless of overlays.
    """
    idx = _ax_index(axtree)
    best = None
    for bid, props in extra.items():
        bbox = props.get("bbox")
        if not bbox:
            continue
        vis = props.get("visibility")
        if vis is not None and vis < 0.5:
            continue
        bx, by, bw, bh = bbox
        if not (bx <= x <= bx + bw and by <= y <= by + bh):
            continue
        role, name = _role_name(idx.get(bid))
        if role not in MOLMOWEB_ROLES or not name:
            continue
        dist = ((bx + bw / 2 - x) ** 2 + (by + bh / 2 - y) ** 2) ** 0.5
        key = (dist, max(bw * bh, 1.0))
        if best is None or key < best[0]:
            best = (key, bid, role, name, bool(props.get("clickable")))
    if best is None:
        return None
    _, bid, role, name, clickable = best
    return {"bid": bid, "role": role, "name": name, "clickable": clickable}


def describe_click(target: dict | None, button: str = "left", double: bool = False) -> str:
    """Render MolmoWeb's click description, matching the released corpus's
    phrasing (`... with value '...' (element is clickable)`)."""
    verb = "dblclick" if double else "click"
    if target is None:
        # No element owns this point. The corpus's own fallback for an
        # unresolved bid is the closest in-vocabulary string available.
        return f"{button} {verb} on element (element is not clickable)"
    suffix = "clickable" if target["clickable"] else "not clickable"
    who = f"{target['role']} with value '{target['name']}'" if target["name"] else target["role"]
    return f"{button} {verb} on {who} (element is {suffix})"


def describe_scroll(delta_x: float, delta_y: float) -> str:
    """MolmoWeb reports scrolls in pixels; this harness natively uses percent.

    Mirrors the *released corpus*, not the current repo's Scroll.describe(): the
    corpus keeps the sign ('scroll up by -142.0 pixels', 516 down / 142 up in a
    300-trajectory sample) whereas today's describe() applies abs(). The dataset
    was built with the earlier formatter, and the dataset is what the model saw.
    """
    if delta_x == 0:
        return f"scroll {'down' if delta_y > 0 else 'up'} by {delta_y} pixels"
    if delta_y == 0:
        return f"scroll {'right' if delta_x > 0 else 'left'} by {delta_x} pixels"
    return f"scroll ({delta_x}, {delta_y}) pixels"


def describe_type(text: str) -> str:
    return f"type '{text}'"


def describe_goto(url: str) -> str:
    return f"go to {url}"


def describe_press(keys: list[str]) -> str:
    # The corpus spells the Ctrl/Cmd modifier as Playwright's platform-neutral
    # "ControlOrMeta" (e.g. "press ControlOrMeta+a key").
    norm = ["ControlOrMeta" if k in ("Control", "Meta") else k for k in keys]
    return f"press {'+'.join(norm)} key"


def describe_wait() -> str:
    # Corpus phrasing ("the page"); today's Noop.describe() says "for page".
    return "wait for the page to finish loading"


def describe_go_back() -> str:
    return "go back to the previous web page on the same browser tab"


def describe_done(msg: str) -> str:
    return f"send message to user: '{msg}'"


# ---------------------------------------------------------------------------
# Compound actions (repetition corpus only)
# ---------------------------------------------------------------------------
# These three are NOT MolmoWeb actions. They were synthesised by OpenWebRL's
# repetition relabelling, so their training feedback is already in this repo's
# own backticked style -- verified against the corpus:
#     Succeed: `scroll_repeat` down x3 executed.
#     Succeed: `click_repeat` x2 executed.
#     Succeed: `click_and_type` executed.
# The harness additionally appends "(<sub-messages>)", which training never had,
# and with the shim enabled those sub-messages would themselves be translated --
# yielding a hybrid string present in neither corpus. So these describers exist
# to reproduce the training form exactly, not to translate anything.

def describe_scroll_repeat(direction: str, times: int) -> str:
    return f"`scroll_repeat` {direction} x{times} executed."


def describe_click_repeat(times: int) -> str:
    return f"`click_repeat` x{times} executed."


def describe_click_and_type() -> str:
    return "`click_and_type` executed."
